import { GoogleGenAI, Type } from "@google/genai";
import { AnalysisData, Risk, Task } from "../types";

const parseAnalysis = (jsonString: string, projectName: string): AnalysisData => {
  try {
    // Clean up potential Markdown code blocks
    const cleanJson = jsonString.replace(/```json\n?|```/g, "").trim();
    const parsed = JSON.parse(cleanJson);
    
    // Transform API response to our internal structure
    const risks: Risk[] = parsed.risks.map((r: any, index: number) => ({
      id: `generated-risk-${index}`,
      threat: r.threat,
      probability: r.probability,
      mitigation: r.mitigation,
      severity: r.severity?.toLowerCase() || 'medium',
      selected: false
    }));

    const tasks: Task[] = parsed.tasks.map((t: any, index: number) => ({
      id: `generated-task-${index}`,
      description: t.description,
      isCompleted: false
    }));

    return {
      projectName,
      risks,
      tasks
    };
  } catch (error) {
    console.error("Failed to parse Gemini response", error);
    throw new Error("Analysis failed: Invalid data format received from AI.");
  }
};

export const analyzeProject = async (projectDescription: string): Promise<AnalysisData> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing. Please check your environment configuration.");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const systemInstruction = `
    You are the "Project Launcher" Strategy Engine. Your role is to act as a high-level mission control computer. 
    Analyze user project ideas with a focus on critical realism and tactical execution.
    Tone: Technical, precise, professional, "Mission Control" aesthetic.
  `;

  const prompt = `
    Analyze the following mission parameter (project brief): "${projectDescription}".
    
    Generate a strategic analysis with two components:
    
    1. PRE-MORTEM (Threat Assessment):
       Identify 3-5 critical failure points or risks. 
       For each, assign a probability score (0-100%), a severity level (critical, high, medium, low), and provide a concise, tactical mitigation strategy.
    
    2. ATOMIZER (Execution Protocol):
       Break the execution down into exactly 10 actionable, sequential micro-steps required to launch this project.
    
    Return the output in strict JSON format.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        systemInstruction: systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            risks: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  threat: { type: Type.STRING, description: "The specific risk or threat" },
                  probability: { type: Type.INTEGER, description: "Probability percentage 0-100" },
                  severity: { 
                    type: Type.STRING, 
                    enum: ["critical", "high", "medium", "low"],
                    description: "Impact severity level if risk occurs" 
                  },
                  mitigation: { type: Type.STRING, description: "Tactical mitigation strategy" }
                },
                required: ["threat", "probability", "severity", "mitigation"]
              }
            },
            tasks: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  description: { type: Type.STRING, description: "Actionable micro-step description" }
                },
                required: ["description"]
              }
            }
          },
          required: ["risks", "tasks"]
        }
      }
    });

    const text = response.text;
    if (!text) throw new Error("No response generated by AI.");

    return parseAnalysis(text, projectDescription);
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generateManifesto = async (projectName: string, mitigations: string[]): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing.");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const prompt = `
    Project: ${projectName}

    Context:
    The user has reviewed the risks for this project and has explicitly decided to IMPLEMENT the following mitigation strategies to fortify the mission:
    ${mitigations.map((m, i) => `${i + 1}. ${m}`).join('\n')}

    Task:
    Rewrite the underlying business plan as a "Strategic Manifesto". 
    This should be a professional, high-energy, and engaging document (approx 250-300 words).
    
    Requirements:
    - Format: Markdown (use bolding for emphasis).
    - Tone: Confident, strategic, and "Mission Ready".
    - Content: State the revised vision. Explicitly mention how the selected mitigation strategies have been integrated into the core workflow to ensure success. 
    - Structure: Start with a "Mission Directive" statement, followed by the "Operational Pivot" (the changes), and end with a "Success Protocol" summary.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });
    
    return response.text || "Mission parameters updated, but manifesto generation was interrupted.";
  } catch (error) {
    console.error("Manifesto generation failed:", error);
    throw new Error("Failed to generate manifesto.");
  }
};